---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Log in (obtain access token)
      redhat.openshift.openshift_auth:
        username: admin
        password: "{{ ocp_password }}"
        host: "{{ ocp_api }}"
        validate_certs: false
      register: openshift_auth_results

    - name: Get AAP Admin Cred
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: aap-admin-password
        namespace: aap
        host: "{{ ocp_api }}"
        api_key: "{{ openshift_auth_results['openshift_auth']['api_key'] }}"
        validate_certs: false
      register: aap_pass

    - name: Get AAP Gateway URL
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Route
        name: aap
        namespace: aap
        host: "{{ ocp_api }}"
        api_key: "{{ openshift_auth_results['openshift_auth']['api_key'] }}"
        validate_certs: false
      register: aap_host

    - name: Set AAP Creds
      ansible.builtin.set_fact:
        aap_hostname: "{{ aap_host['resources'][0]['spec']['host'] }}"
        aap_username: "{{ aap_username |default('admin') }}"
        aap_password: "{{ aap_pass['resources'][0]['data']['password'] | ansible.builtin.b64decode }}"



  tasks:
    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: "{{ aap_configs_dir | default((lookup('env', 'AAP_CONFIGS_DIR') == '') | ternary('configs', lookup('env', 'AAP_CONFIGS_DIR'))) }}"
        ignore_files: [controller_config.yml.template]
        extensions: [yml]
      tags:
        - always

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
