apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-ansible-collection-ci-68twsu
  namespace: aap
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: admin
        generateName: ansible-collection-ci-
        labels:
          tekton.dev/pipeline: ansible-collection-ci
        namespace: aap
      spec:
        params:
          - name: collection-url
            value: $(tt.params.git-repo-url)
          - name: collection-repo-version
            value: $(tt.params.git-revision)
          - name: playbook-repo
            value: 'https://github.com/mdidato/ansible_bootcamp_enablement.git'
        pipelineRef:
          name: ansible-collection-ci
        status: null
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: ocs-external-storagecluster-ceph-rbd
                volumeMode: Filesystem
